import type { Institution } from "@/types";

/** 研究机构 mock 数据 —— 高校 / 研究院 / 企业实验室各覆盖 */
export const institutions: Institution[] = [
  {
    id: "tsinghua",
    nameCn: "清华大学",
    nameEn: "Tsinghua University",
    initials: "THU",
    logoColor: "#174A7E",
    type: "高校",
    location: "中国 · 北京",
    intro:
      "清华大学计算机系始建于 1958 年,是国内计算机学科的发源地之一。在人工智能领域拥有智能技术与系统国家重点实验室、清华 AI 研究院(THUAI)等平台,姚期智院士领衔的交叉信息研究院(姚班)培养了大批顶尖 AI 人才。近年来在大模型(智谱 GLM 系列源头)、类脑计算、具身智能方向产出持续领先。",
    stats: [
      { label: "研究人员", value: "3,800+" },
      { label: "年论文", value: "1,200+" },
      { label: "总引用", value: "2.4M" },
      { label: "国家级平台", value: "12" },
    ],
    fields: ["大语言模型", "计算机视觉", "类脑计算", "具身智能"],
    highlight: "代表性成果:GLM 系列大模型、天机芯类脑芯片(《Nature》封面)。",
    bookmarked: true,
    rank: 1,
    papersPerYear: 1200,
  },
  {
    id: "cas-ict",
    nameCn: "中科院计算技术研究所",
    nameEn: "Institute of Computing Technology, CAS",
    initials: "ICT",
    logoColor: "#0E7490",
    type: "研究院",
    location: "中国 · 北京",
    intro:
      "中科院计算所成立于 1956 年,是中国计算机事业的摇篮,研制了我国第一台通用数字电子计算机。孵化了联想、曙光、寒武纪等企业。在处理器芯片(龙芯、寒武纪)、智能计算系统方向处于国内领先地位,拥有处理器芯片全国重点实验室。",
    stats: [
      { label: "研究人员", value: "1,600+" },
      { label: "年论文", value: "600+" },
      { label: "总引用", value: "890k" },
      { label: "国家级平台", value: "8" },
    ],
    fields: ["AI 芯片", "智能计算系统", "体系结构", "数据科学"],
    highlight: "代表性成果:寒武纪系列 AI 处理器、龙芯 CPU。",
    rank: 4,
    papersPerYear: 600,
  },
  {
    id: "pku",
    nameCn: "北京大学",
    nameEn: "Peking University",
    initials: "PKU",
    logoColor: "#B91C1C",
    type: "高校",
    location: "中国 · 北京",
    intro:
      "北京大学信息科学技术学院与智能学院在机器学习理论、计算机视觉、自然语言处理方向实力雄厚。王选计算机研究所曾以汉字激光照排技术闻名。近年依托北京通用人工智能研究院(BIGAI)在通用人工智能、多模态理解方向布局深入。",
    stats: [
      { label: "研究人员", value: "2,900+" },
      { label: "年论文", value: "900+" },
      { label: "总引用", value: "1.6M" },
      { label: "国家级平台", value: "9" },
    ],
    fields: ["机器学习理论", "多模态理解", "NLP", "智能系统"],
    highlight: "代表性成果:汉字激光照排系统、通用智能体 Tong 系列。",
    rank: 3,
    papersPerYear: 900,
  },
  {
    id: "mit-csail",
    nameCn: "MIT 计算机科学与人工智能实验室",
    nameEn: "MIT CSAIL",
    initials: "CSAIL",
    logoColor: "#A31F34",
    type: "高校",
    location: "美国 · 剑桥",
    intro:
      "CSAIL 是 MIT 最大的跨学科实验室,由 1963 年的 Project MAC 演变而来,2003 年合并 AI Lab 与 LCS 而成。诞生了分时操作系统、RSA 加密、万维网雏形等奠基性成果。现有 60+ 研究组,覆盖机器人、机器学习、系统、理论计算全谱系,何恺明等知名学者在此任教。",
    stats: [
      { label: "研究人员", value: "1,700+" },
      { label: "年论文", value: "800+" },
      { label: "总引用", value: "3.1M" },
      { label: "国家级平台", value: "15" },
    ],
    fields: ["机器人", "表征学习", "系统与网络", "计算理论"],
    highlight: "代表性成果:ResNet(何恺明)、RSA 加密算法、World Wide Web 发源地之一。",
    rank: 2,
    papersPerYear: 800,
  },
  {
    id: "stanford-sail",
    nameCn: "斯坦福人工智能实验室",
    nameEn: "Stanford AI Lab (SAIL)",
    initials: "SAIL",
    logoColor: "#8C1515",
    type: "高校",
    location: "美国 · 斯坦福",
    intro:
      "SAIL 由 John McCarthy 于 1963 年创立,是人工智能学科的发源地之一('Artificial Intelligence'一词的诞生地)。李飞飞曾任实验室主任并创立 ImageNet。当前在基础模型(CRFM/HELM 评测体系)、机器人学习、AI 医疗方向引领全球研究。",
    stats: [
      { label: "研究人员", value: "900+" },
      { label: "年论文", value: "500+" },
      { label: "总引用", value: "2.2M" },
      { label: "国家级平台", value: "7" },
    ],
    fields: ["基础模型", "机器人学习", "AI 医疗", "计算机视觉"],
    highlight: "代表性成果:ImageNet、HELM 基础模型评测体系、Stanford Doggo 机器人。",
    rank: 5,
    papersPerYear: 500,
  },
  {
    id: "deepmind",
    nameCn: "Google DeepMind",
    nameEn: "Google DeepMind",
    initials: "DM",
    logoColor: "#4285F4",
    type: "企业实验室",
    location: "英国 · 伦敦",
    intro:
      "DeepMind 2010 年成立于伦敦,2014 年被 Google 收购,2023 年与 Google Brain 合并为 Google DeepMind。以 AlphaGo、AlphaFold(2024 诺贝尔化学奖)、Gemini 系列模型闻名,是强化学习与科学 AI(AI for Science)的标杆实验室。CEO Demis Hassabis 为认知神经科学背景的 AI 先驱。",
    stats: [
      { label: "研究人员", value: "2,500+" },
      { label: "年论文", value: "700+" },
      { label: "总引用", value: "1.9M" },
      { label: "国家级平台", value: "—" },
    ],
    fields: ["强化学习", "蛋白质结构预测", "基础模型", "AI for Science"],
    highlight: "代表性成果:AlphaGo、AlphaFold(诺贝尔化学奖)、Gemini 系列。",
    rank: 6,
    papersPerYear: 700,
  },
  {
    id: "openai",
    nameCn: "OpenAI",
    nameEn: "OpenAI",
    initials: "OAI",
    logoColor: "#10A37F",
    type: "企业实验室",
    location: "美国 · 旧金山",
    intro:
      "OpenAI 2015 年由 Sam Altman、Elon Musk、Ilya Sutskever 等创立,使命是确保通用人工智能惠及全人类。GPT 系列模型开启了生成式 AI 时代,ChatGPT 成为史上增长最快的消费级应用。研究方向覆盖对齐、推理模型(o 系列)、多模态与智能体。",
    stats: [
      { label: "研究人员", value: "1,200+" },
      { label: "年论文", value: "200+" },
      { label: "总引用", value: "1.4M" },
      { label: "国家级平台", value: "—" },
    ],
    fields: ["大语言模型", "对齐与安全", "多模态", "智能体"],
    highlight: "代表性成果:GPT 系列、ChatGPT、DALL·E、Sora。",
    bookmarked: true,
    rank: 7,
    papersPerYear: 200,
  },
  {
    id: "mila",
    nameCn: "Mila 魁北克人工智能研究所",
    nameEn: "Mila - Quebec AI Institute",
    initials: "MILA",
    logoColor: "#F59E0B",
    type: "研究院",
    location: "加拿大 · 蒙特利尔",
    intro:
      "Mila 由图灵奖得主 Yoshua Bengio 于 1993 年创立,是全球最大的深度学习学术研究中心之一,聚集了 1,000+ 研究人员。在生成模型(GAN 诞生地之一)、因果推断、AI 气候与医疗应用方向特色鲜明,与蒙特利尔大学、McGill 大学深度联动。",
    stats: [
      { label: "研究人员", value: "1,000+" },
      { label: "年论文", value: "450+" },
      { label: "总引用", value: "980k" },
      { label: "国家级平台", value: "3" },
    ],
    fields: ["深度学习", "因果推断", "生成模型", "AI 公益应用"],
    highlight: "代表性成果:GAN 早期工作、神经机器翻译注意力机制奠基性论文。",
    rank: 8,
    papersPerYear: 450,
  },
];
