import type { Patent } from "@/types";

/** 专利库 mock 数据 —— AI 领域,覆盖 5 个技术领域 */
export const patents: Patent[] = [
  {
    id: "p-1",
    title: "一种基于扩散模型的视频帧插值生成方法",
    applicationNo: "CN202410123456.7",
    applicant: "清华大学",
    publishedAt: "2025-03-14",
    field: "计算机视觉",
    status: "实质审查",
    kind: "发明",
    citations: 12,
  },
  {
    id: "p-2",
    title: "大语言模型多智能体协同推理系统及方法",
    applicationNo: "CN202410234567.8",
    applicant: "北京智源人工智能研究院",
    publishedAt: "2025-01-22",
    field: "自然语言处理",
    status: "已授权",
    kind: "发明",
    citations: 38,
  },
  {
    id: "p-3",
    title: "一种长上下文 Transformer 稀疏注意力加速方法",
    applicationNo: "CN202310345678.9",
    applicant: "华为技术有限公司",
    publishedAt: "2024-11-08",
    field: "机器学习",
    status: "已授权",
    kind: "发明",
    citations: 54,
  },
  {
    id: "p-4",
    title: "基于视觉语言模型的机器人抓取姿态生成方法",
    applicationNo: "CN202410456789.0",
    applicant: "上海交通大学",
    publishedAt: "2025-05-30",
    field: "智能机器人",
    status: "已公开",
    kind: "发明",
    citations: 6,
  },
  {
    id: "p-5",
    title: "存算一体 AI 芯片的片上数据调度方法",
    applicationNo: "CN202310567890.1",
    applicant: "中科院计算技术研究所",
    publishedAt: "2024-08-19",
    field: "芯片与系统",
    status: "已授权",
    kind: "发明",
    citations: 41,
  },
  {
    id: "p-6",
    title: "一种多模态医学影像分割模型的训练方法",
    applicationNo: "CN202410678901.2",
    applicant: "腾讯健康(深圳)有限公司",
    publishedAt: "2025-02-11",
    field: "计算机视觉",
    status: "实质审查",
    kind: "发明",
    citations: 9,
  },
  {
    id: "p-7",
    title: "面向检索增强生成的文档切分与索引构建方法",
    applicationNo: "PCT/CN2024/123456",
    applicant: "阿里巴巴达摩院",
    publishedAt: "2024-12-03",
    field: "自然语言处理",
    status: "PCT",
    kind: "发明",
    citations: 23,
  },
  {
    id: "p-8",
    title: "一种模型量化感知训练的混合精度分配装置",
    applicationNo: "CN202420789012.3",
    applicant: "寒武纪科技",
    publishedAt: "2024-09-25",
    field: "芯片与系统",
    status: "已授权",
    kind: "实用新型",
    citations: 15,
  },
  {
    id: "p-9",
    title: "基于强化学习的四足机器人步态自适应控制方法",
    applicationNo: "CN202410890123.4",
    applicant: "宇树科技",
    publishedAt: "2025-06-17",
    field: "智能机器人",
    status: "已公开",
    kind: "发明",
    citations: 4,
  },
  {
    id: "p-10",
    title: "一种联邦学习场景下的梯度压缩传输方法",
    applicationNo: "CN202310901234.5",
    applicant: "北京邮电大学",
    publishedAt: "2024-06-28",
    field: "机器学习",
    status: "已授权",
    kind: "发明",
    citations: 29,
  },
];

/** 法律状态标签(左栏 chips,装饰性,同 LibraryPanel 标签) */
export const patentStatuses = ["已授权", "实质审查", "已公开", "PCT 国际申请"];
